/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos_view;

import javax.swing.JFrame;
import pos_controller.admin_controller;

/**
 *
 * @author Ashir Ali
 */
public class add_item extends javax.swing.JFrame {

    /**
     * Creates new form add_item
     */
    public add_item() {
        initComponents();
    this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.eclipse.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add a Item:");
        jPanel1.add(jLabel10, new org.eclipse.lib.awtextra.AbsoluteConstraints(140, 40, 180, 30));
        jPanel1.add(jSeparator1, new org.eclipse.lib.awtextra.AbsoluteConstraints(60, 90, 640, 30));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("U:\\.UNIVERSITY\\Semester 5\\OOAD Lab\\Final\\Updated\\project\\src\\Images/Webp.net-resizeimage (8).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.eclipse.lib.awtextra.AbsoluteConstraints(60, 20, 70, -1));

        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel1.add(jSeparator3, new org.eclipse.lib.awtextra.AbsoluteConstraints(140, 70, 130, 10));

        jSeparator4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel1.add(jSeparator4, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 230, 240, 10));

        jSeparator5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jSeparator5.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel1.add(jSeparator5, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 300, 240, 20));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Stock:");
        jPanel1.add(jLabel8, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Price:");
        jPanel1.add(jLabel9, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jSeparator6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jSeparator6.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel1.add(jSeparator6, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 360, 530, 20));

        jLabel12.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bar Code:");
        jPanel1.add(jLabel12, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name:");
        jPanel1.add(jLabel11, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        jSeparator7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jSeparator7.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel1.add(jSeparator7, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 170, 240, 10));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 380, 150, 40));

        jTextField1.setBackground(new java.awt.Color(36, 47, 65));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 330, 530, 30));

        price.setBackground(new java.awt.Color(36, 47, 65));
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setToolTipText("");
        price.setBorder(null);
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 200, 230, 30));

        name.setBackground(new java.awt.Color(36, 47, 65));
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setToolTipText("");
        name.setBorder(null);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 140, 230, 30));

        stock.setBackground(new java.awt.Color(36, 47, 65));
        stock.setForeground(new java.awt.Color(255, 255, 255));
        stock.setToolTipText("");
        stock.setBorder(null);
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        jPanel1.add(stock, new org.eclipse.lib.awtextra.AbsoluteConstraints(160, 270, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String n=name.getText();
          int p=Integer.parseInt(price.getText());
          int s=Integer.parseInt(stock.getText());
          admin_controller control=new admin_controller();
          control.add_item(n, p, s);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
